services:
  - type: web
    name: wt-team-stats
    env: python
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:server --bind 0.0.0.0:$PORT --timeout 120
    autoDeploy: true